### ISSUE TITLE
Handling Late-Offer Re-invites

### ISSUE THREAD

**Issue by sudermanjr** [havfo/WEBRTC-to-SIP#10]
Hi,

I am using the project as a the basis for a webrtc -> Sip gateway, and I am seeing an issue with late-offer reinvites that I was wondering if you could shed some light on.  In this WebRTC -> SIP call flow, the sip endpoint sends back a re-invite with no media info, and then later sends an ACK with the media info in it.  Right now the config does not handle this properly, and passes the ack straight through to the webrtc client, which then breaks the flow because the ack does not send DTLS and SRTP information.  I have looked through the flow and I am not sure how to change this.  It seems like something that could be done, but I don't know kamailio well enough yet to change it.  

Any suggestions you can provide would be very helpful.

Thanks,
Andrew

**Comment by havfo** [comment]
Hi,

I have re-written parts of the config for better handling of late-offer re-invites, could you test the new config?

**Comment by sudermanjr** [comment]
I managed to get it working in my config, but it was a little hacky.  Looks like you changed the config pretty extensively.  I will try to find time to test it in our setup at some point.  Thanks!
