### ISSUE TITLE
file flavors/no_ngcp not found

### ISSUE THREAD

**Issue by kossivi1984** [havfo/WEBRTC-to-SIP#12]
Install RTPEngine

git clone https://github.com/sipwise/rtpengine.git
cd rtpengine
./debian/flavors/no_ngcp

I use ubuntun and i don't see the /flavors/no_ngcp

can i help me with the ubuntu configuration ?

**Comment by havfo** [comment]
Seems RtpEngine has updated their build instructions. Take a look under: https://github.com/sipwise/rtpengine#on-a-debian-system

I will update this repository when I have time.

**Comment by kossivi1984** [comment]
Thanks very much. Can i help me with kamailio msrp and webRTC client implamentation ?

**Comment by havfo** [comment]
I'm sorry, but I don't have time to help at the moment. However, if you need configuration for MSRP relay in Kamailio, Sipwise has a nice example configuration at: https://github.com/sipwise/kamailio/blob/master/misc/examples/webrtc/websocket.cfg

**Comment by kossivi1984** [comment]
Thank you very much for your first supports. These setup supports help me understand a lot and move forward.
Which webRTC client is used, for performing the messages, sending the file, video call and screen sharing (or desktop remote access) ? Thank you for helping me if you have documents or link

**Comment by kossivi1984** [comment]
Hello,
I really need your help on my project.
1- MSRP configuration on kamailio
2- Choice of a WebRTC client supporting MSRP
3- Connection of kamailio and WebRTC for to develop the services like video call, chat, transfer of files, to take control of a machine at a distance

**Comment by havfo** [comment]
This project does not handle MSRP, nor does the example-client (SIP.js) support MSRP. The focus in this repository is supporting SIP.
