### ISSUE TITLE
chat error

### ISSUE THREAD

**Issue by dipenpatel235** [havfo/WEBRTC-to-SIP#13]
hello..
i have done this setup but chat is not working..
getting error when sending message 

here i have attached screenshot
![capture](https://user-images.githubusercontent.com/8135097/37655934-9ccceb50-2c6c-11e8-836d-ac08ecceaee9.PNG)

**Comment by havfo** [comment]
Hi, I have not tested the chat functionality, that has not been a priority for me. It seems to be a 404 message from Kamailio from the screenshot. Have you created the users 1001 and 1002, and are they logged on?

**Comment by dipenpatel235** [comment]
Ok...It is worked fine now.
Need to create two user  so both user have different url
Like
Https://domain.com/one
Https://domain.com/two

Then invite chat and work fine.


Thanks

**Comment by dipenpatel235** [comment]
But now one more issue is
Webrtc to webrtc call not working
Getting SDP error

Webrtc - sip work fine
