### ISSUE TITLE
can i run all of in same server?

### ISSUE THREAD

**Issue by bunalng** [havfo/WEBRTC-to-SIP#14]
i want to know i can install Server - Kamailio + RTPEngine + Nginx (WEBRTC client) and Server - TURN on same server? or what?

**Comment by havfo** [comment]
Yes, absolutely, but it has some consequenses.

The default setup of the servers have everything on port 443. This is to avoid, as much as possible, beeing blocked  by firewalls. This means that the different services has to be spread among several servers to be able to listen on port 443.

What you can do is change TURN server to listen on default port, or some other port than 443. Change it in the [turn config.](https://github.com/havfo/WEBRTC-to-SIP/blob/master/etc/turnserver.conf)

**Comment by havfo** [comment]
This is now possible using streams in nginx 1.15, will update repo.

**Comment by mbunal** [comment]
Wonderfull news...

**Comment by havfo** [comment]
Support has been added, still need to update README.

**Comment by havfo** [comment]
Done
