### ISSUE TITLE
can the RTPEngine component replaced by Kurento?

### ISSUE THREAD

**Issue by deltapath-eric** [havfo/WEBRTC-to-SIP#15]
AFAIK the Kurento kind of also able to do something like DTLS-SRTP to RTP

If this able to done, the entire project will be more friendly on commercial use :)

**Comment by havfo** [comment]
The architecture would have to change for this to work. Kamailio does not have a module for interfacing with Kurento directly. I also have a repository that has Kurento in the mix, [Kurento-Nodejs-SIP
](https://github.com/havfo/Kurento-Nodejs-SIP), but not as a basic gateway/SBC. I suppose a way to do it could be to have the WEBRTC client connect to a Nodejs server that handles Kurento. That way it would appear as regular RTP when it arrives at Kamailio.

**Comment by deltapath-eric** [comment]
Thanks a lot for the direction! I will take a look on the following 
https://github.com/kirm/sip.js
which maybe the miss part (nodejs server, but not yet handles Kurento), will try when have time.
