### ISSUE TITLE
iptables.sh issue

### ISSUE THREAD

**Issue by salihy** [havfo/WEBRTC-to-SIP#16]
I get error when running iptables.sh script. I use Debian 9, and installed kamailio from debs in http://deb.kamailio.org/

```
iptables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
```

the location of error is this
```
# RTPEngine
$IPTABLES -I INPUT -p udp -j RTPENGINE --dport $RTP --id 0
$IP6TABLES -I INPUT -p udp -j RTPENGINE --dport $RTP --id 0
```

Thank you for your help.

**Comment by havfo** [comment]
Have you installed RTPEngine?

**Comment by salihy** [comment]
Yes, I installed as described, but there was no ./debian/flavors/no_ngcp executable, and I skipped that step.

**Comment by havfo** [comment]
This could mean that the RTPEngine kernel module has not been installed. Did all the RTPEngine .deb files get installed correctly and did the kernel module get built?

**Comment by salihy** [comment]
I tried on a clean server again and same error, could you please try it? 
I used debian 9.4.0 netinst iso, and installed rtpengine from git.
