### ISSUE TITLE
reinvite after iceRestart does not work

### ISSUE THREAD

**Issue by bearinld004** [havfo/WEBRTC-to-SIP#19]
Just wondering if you have any issue with doing a re-invite after doing an ice restarts. (this will force a new sdp, icecandidates, ice ufrag pwd ). This forces rtpengine to fix its ports for the new setting. 
the webrtc rtpengine side is fine but the rtpengine pstn gateway side gets no audio after this reinvite.

Anyways I'm trying to jump between networks on mobile devices. like wifi to wifi, wifi to mobile, mobile to wifi, i detect a disconnect and do an ice restart. I'm also using sipjs 0.11.3 to help me with signalling between kamailio and webrtc.

**Comment by havfo** [comment]
Have not tested that scenario, so can't really help a lot. After the iceRestart the WebRTC client sends a SIP reINVITE? Is this reINVITE responded to by the other side (PSTN)?

**Comment by bearinld004** [comment]
@havfo yes after ice restart i send the sdp to the other side. the other side does respond to it with a 200OK, but then audio stops flowing. I do observe that rtpengine detects dtmf on the webrtc leg.
Maybe my PSTN gateway provider does not support reinvite

Is it possible to reinvite without relaying it to the other side? it seems like the reinvite does provide the fix for the jumping network on webrtc side but breaks the audio on the sip gateway side.

**Comment by bearinld004** [comment]
Actually rtpengine seems to detect dtmf from both side after the reinvite but it just doesnt comeout of either end.
