### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by mSys-mislav** [havfo/WEBRTC-to-SIP#20]
When running command :
# ./debian/flavors/no_ngcp
-bash: ./debian/flavors/no_ngcp: No such file or directory

How to fix this?

**Comment by mSys-mislav** [comment]
I've managed to work through dependencies anyway, but in the log I can see this:

> Sep 26 10:18:14 test2 systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Sep 26 10:18:14 test2 systemd[1]: Failed to reset devices.list on /system.slice: Invalid argument
Sep 26 10:18:14 test2 kernel: [72573.683715] Registering xt_RTPENGINE module - version 6.5.0.0+0~mr6.5.0.0
Sep 26 10:18:15 test2 rtpengine: CRIT: Fatal error: Bad command line: No such file or directory
Sep 26 10:18:15 test2 rtpengine[22402]: [1537949895.131655] CRIT: Fatal error: Bad command line: No such file or directory
Sep 26 10:18:15 test2 systemd[1]: ngcp-rtpengine-daemon.service: main process exited, code=exited, status=255/n/a
Sep 26 10:18:16 test2 kernel: [72574.987074] Unregistering xt_RTPENGINE module
Sep 26 10:18:16 test2 systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.
Sep 26 10:18:16 test2 systemd[1]: Unit ngcp-rtpengine-daemon.service entered failed state.
Sep 26 10:18:16 test2 systemd[1]: Reloading.


What seems to be a problem?

**Comment by havfo** [comment]
I have not updated RtpEngine build instructions in a while, so there might have been updates. Have you checked out RtpEngine on github? I will try to update the build instructions in the near future.
