### ISSUE TITLE
SIP Client with WebRTC SDP

### ISSUE THREAD

**Issue by ForGuru** [havfo/WEBRTC-to-SIP#21]
I am creating a SIP client with WebRCT SDP. I am able to create call between clients.

I just to in Kamailio that if Client has WebRCT SDP or Normal SDP. If client has Normal SDP then I will engage RTPENGINE to transcode. 

How can I do that ?

**Comment by havfo** [comment]
I can see at least two ways of doing it.

1. You can listen for failure 488 Not Acceptable Here, engage RtpEngine, and retry.

2. Search SDP for normal or webrtc features, and engage based on findings.

Please let me know if you want me to ellaborate further.
