### ISSUE TITLE
Parallel call forking case

### ISSUE THREAD

**Issue by korayvt** [havfo/WEBRTC-to-SIP#22]
Hi,
In the parallel call forking case where branches have different media requirements, for example one branch is SDES while the other one is DTLS, it's needed to tell rtpengine that those are different branches. There is an option in rtpengine_manage function for this purpose. It's via_branch option with extra_id_pv variable. 
Do you have any idea on how we can integrate the usage of this option in rtpengine offer and answer commands in a simplest way?

**Comment by havfo** [comment]
I would probably add a branch flag to the different branches. I have made a gist with some changes to the existing config [here](https://gist.github.com/havfo/f35fd96ea1947b2b3fa974f06b854523).

The changes i have made are in:
[route\[WEB_SIP\]](https://gist.github.com/havfo/f35fd96ea1947b2b3fa974f06b854523#file-kamailio-cfg-L679) and [route\[NATMANAGE\]](https://gist.github.com/havfo/f35fd96ea1947b2b3fa974f06b854523#file-kamailio-cfg-L552).

In the rtpengine_manage calls in NATMANAGE, you could add the via-branch parameter to apply it to the correct one. I have not used the via-branch flag myself, but i guess via-branch=auto should work.

Note: the config does not run as is, it is only an example to explain.

**Comment by havfo** [comment]
And of course you would have to restructure NATMANAGE to your needs.

**Comment by korayvt** [comment]
The tricky part is what via-branch value should be used. 

After some testing I realized that 'auto' option is not working. There is no code implementing this parameter. 

Moreover all forked branches have the same via branch id which is the incoming INVITE's via branch id on branch route. So the values 1 and 2 to via-branch option is not functional in this case. 

Therefore we have only 'extra' option with extra_pv_id variable.
And the question is what value do we need to set to this variable in requests on branch route and corresponding responses on reply route?

**Comment by havfo** [comment]
I have never had the need to set different branches myself, so not sure how much help I can be here.

In the example config above, the flag for SDES/DTLS is set pr. branch. So I guess you do something like:
```
if (isbflagset(FLB_SDES)) {
   $avp(extra_id) = "sdes";
   rtpengine_manage("...via-branch=extra...");
}
```

**Comment by havfo** [comment]
You might find some inspiration from [this](https://www.mail-archive.com/sr-users@lists.sip-router.org/msg30895.html) forum post.

**Comment by havfo** [comment]
You inspired me to update the kamailio config. It should now be able to handle different branches with different bridging cases.
