### ISSUE TITLE
E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by webrtcccccc** [havfo/WEBRTC-to-SIP#24]
root@debian-pc:~/rtpengine# apt-get install -y ngcp-rtpengine
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ngcp-rtpengine : Depends: ngcp-rtpengine-daemon (>= 7.1.1.5+0~mr7.1.1.5) but it is not going to be installed
                  Depends: ngcp-rtpengine-recording-daemon (>= 7.1.1.5+0~mr7.1.1.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by yboujraf** [comment]
Hi Dear,

I figure out an issue when trying to install the rtpengine deb packages.

> echo 'deb http://deb.sipwise.com/spce/mr7.1.1/ stretch main' > /etc/apt/sources.list.d/sipwise.list
echo 'deb-src http://deb.sipwise.com/spce/mr7.1.1/ stretch main' >> /etc/apt/sources.list.d/sipwise.list
apt-get update
apt-get install -y --allow-unauthenticated ngcp-keyring
apt-get update
apt-get install -y ngcp-rtpengine

??? Missing PUBKEY.

Thanks if you have any idea. In the meantime, I am using Debian Buster same issue.

Best Regards,
Youssef

**Comment by havfo** [comment]
Try installing the key manually: `wget -q -O - https://deb.sipwise.com/spce/sipwise.gpg | apt-key add -`
