### ISSUE TITLE
Add dispatcher

### ISSUE THREAD

**Issue by furek1** [havfo/WEBRTC-to-SIP#25]
Hi, 
Could you add a dispatcher to your project?
So that calls were made inside kamailio as it finds the user and sent above 9 digits to servers defined in dispatcher?

**Comment by havfo** [comment]
This project is not meant as an advanced routing configuration, but more of an example for translating between WebRTC and SIP. There are plenty of examples for using dispatcher available, I even have another repository that uses dispatcher [here](https://github.com/havfo/Skype-Kamailio-PSTN-gateway).

**Comment by furek1** [comment]
I tried to configure it, but I'm not an expert, can we go to email, irc, jabber? Would you like to help for a small fee?

**Comment by khorsmann** [comment]
@furek1 the learning curve on Kamailio is high. You should read the module documentations and try to adapt the configs in your own lab. If you then have problems you can make qualified questions on the Kamailio mailing list. 

Also on the Kamailio website there is an business directory of consultants if you are looking for paid services for configuration and planing. 

This Github repo is an excellent guide to adapt webrtc to SIP with Kamailio and stuff around it.

Just my thoughts about that.

**Comment by furek1** [comment]
@khorsmann The mailing list is poor, because no one talks there anymore about the dedicated channel :(
