### ISSUE TITLE
No audio from SIP to WS

### ISSUE THREAD

**Issue by chiragd** [havfo/WEBRTC-to-SIP#27]
Hi,

I'm using the WS cfg you've described for kamailio here: https://github.com/havfo/WEBRTC-to-SIP/blob/master/etc/kamailio/kamailio.cfg

I have successful calls from the Web to Kamailio to SIP, but in the reverse direction, the call establishes but there is no audio. 

I'm wondering if you might know of any reason for this happening?

Thanks in advance,

C

**Comment by yboujraf** [comment]
Dear @chiragd 

Did you fixed your issue ?

Thanks if you could share your email.

Best Regards

**Comment by havfo** [comment]
Hard to say. The RTPEngine options for that direction is set here: https://github.com/havfo/WEBRTC-to-SIP/blob/4653d1910621d12a6170cd2ff0e99fb4968ff255/etc/kamailio/kamailio.cfg#L685

What audio codecs are the legacy SIP devices offering? You might need to change the options to RTPEngine depending on what is offered by the legacy side.
