### ISSUE TITLE
NO_PUBKEY Error in debian 10

### ISSUE THREAD

**Issue by vigikaran** [havfo/WEBRTC-to-SIP#30]
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 69D9C21F6D9B587E NO_PUBKEY 022CEFA649AEE1B0

**Comment by havfo** [comment]
Make sure the repo key step is done properly: `wget -q -O - https://deb.sipwise.com/spce/sipwise.gpg | apt-key add -`
