### ISSUE TITLE
could not login sipml5 demo to kamailio via websocket.

### ISSUE THREAD

**Issue by voipmanvn** [havfo/WEBRTC-to-SIP#32]
Hello,
could not register sipml5 client to kamailio server. log do not show anything.

Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14643]: DEBUG: <core> [ip_addr.c:229]: print_ip(): tcpconn_new: new tcp connection: 27.65.211.112
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14643]: DEBUG: <core> [tcp_main.c:985]: tcpconn_new(): on port 60109, type 3
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14643]: DEBUG: <core> [tcp_main.c:1291]: tcpconn_add(): hashes: 1176:2713:3040, 12
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14643]: DEBUG: <core> [io_wait.h:380]: io_watch_add(): DBG: io_watch_add(0x5582ca9d6f40, 33, 2, 0x7f087f196118), fd_no=22
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14643]: DEBUG: <core> [io_wait.h:602]: io_watch_del(): DBG: io_watch_del (0x5582ca9d6f40, 33, -1, 0x0) fd_no=23 called
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14643]: DEBUG: <core> [tcp_main.c:4139]: handle_tcpconn_ev(): sending to child, events 1
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14643]: DEBUG: <core> [tcp_main.c:3818]: send2child(): selected tcp worker 2 13(14638) for activity on [tls:128.199.156.64:4443], 0x7f087f196118
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: <core> [tcp_read.c:1603]: handle_io(): received n=8 con=0x7f087f196118, fd=9
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_server.c:197]: tls_complete_init(): completing tls connection initialization
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_server.c:226]: tls_complete_init(): Using initial TLS domain TLSs<default> (dom 0x7f087f0982f8 ctx 0x7f087f0ce348 sn [])
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_domain.c:724]: sr_ssl_ctx_info_callback(): SSL handshake started
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: <core> [tcp_main.c:2430]: tcpconn_do_send(): sending...
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: <core> [tcp_main.c:2464]: tcpconn_do_send(): after real write: c= 0x7f087f196118 n=4573 fd=9
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: <core> [tcp_main.c:2465]: tcpconn_do_send(): buf=#012#026#003#003
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: <core> [io_wait.h:380]: io_watch_add(): DBG: io_watch_add(0x5582ca9814c0, 9, 2, 0x7f087f196118), fd_no=1
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_domain.c:736]: sr_ssl_ctx_info_callback(): SSL handshake done
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_domain.c:724]: sr_ssl_ctx_info_callback(): SSL handshake started
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_domain.c:728]: sr_ssl_ctx_info_callback(): SSL renegotiation initiated by client
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_domain.c:736]: sr_ssl_ctx_info_callback(): SSL handshake done
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_domain.c:724]: sr_ssl_ctx_info_callback(): SSL handshake started
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_domain.c:728]: sr_ssl_ctx_info_callback(): SSL renegotiation initiated by client
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_domain.c:736]: sr_ssl_ctx_info_callback(): SSL handshake done
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_server.c:413]: tls_accept(): TLS accept successful
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_server.c:420]: tls_accept(): tls_accept: new connection from 27.65.211.112:60109 using TLSv1.3 TLS_AES_256_GCM_SHA384 256
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_server.c:423]: tls_accept(): tls_accept: local socket: 128.199.156.64:4443
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_server.c:434]: tls_accept(): tls_accept: client did not present a certificate
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: tls [tls_server.c:1170]: tls_read_f(): Reading on a renegotiation of connection (n:-1) (2)
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: <core> [tcp_read.c:1370]: tcp_read_req(): EOF
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: <core> [io_wait.h:602]: io_watch_del(): DBG: io_watch_del (0x5582ca9814c0, 9, -1, 0x10) fd_no=2 called
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: <core> [tcp_read.c:1524]: release_tcpconn(): releasing con 0x7f087f196118, state -1, fd=9, id=12 ([27.65.211.112]:60109 -> [27.65.211.112]:4443)
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14638]: DEBUG: <core> [tcp_read.c:1528]: release_tcpconn(): extra_data 0x7f087f1ade00
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14643]: DEBUG: <core> [tcp_main.c:3250]: handle_tcp_child(): reader response= 7f087f196118, -1 from 2
Jul 23 03:17:09 kamailiotesting /usr/local/sbin/kamailio[14643]: DEBUG: tls [tls_server.c:665]: tls_h_close(): Closing SSL connection 0x7f087f1ade00

Thanks

**Comment by havfo** [comment]
I have not tested with sipml5.

**Comment by voipmanvn** [comment]
I have tried

https://ringmeg.uninett.no/

But same issue there, log is same as sipml5.

Could you tell me the issue ?

Thanks

**Comment by havfo** [comment]
It seems like a certificate issue, hard to say. Check date/time on computer. Verify that you have correct certificate settings and CAs installed.
