### ISSUE TITLE
Kamailio + RTPEngine + TURN server behind NAT

### ISSUE THREAD

**Issue by yboujraf** [havfo/WEBRTC-to-SIP#35]
Dear @havfo 

Is your setup is working behind NAT ?

Best Regards

**Comment by havfo** [comment]
Depends what you mean by that. It will work for clients behind NAT, certainly, if that is what you are asking?

**Comment by yboujraf** [comment]
Dear @havfo 

INTERNET <->FIREWALL (PUBLIC_IP) <->NAT1:1 <->PRIVATE_IP<->KAMAILIO/RTPENGINE

![infra v3 1 6](https://user-images.githubusercontent.com/6151258/135849145-016a4055-2574-4050-b76c-3cf2a865569d.png)

Best Regards

**Comment by havfo** [comment]
No, this setup will not work for that scenario. Kamailio and rtpengine certainly can, but not this config. This config is only an example to show a basic setup to bridge between webrtc and legacy sip clients.

**Comment by yboujraf** [comment]
@havfo 

Thanks for the feedback 

What I need to modify or add to be able to get webrtc working behind NAT?

Best regards

**Comment by havfo** [comment]
See my answer to another similar issue https://github.com/havfo/WEBRTC-to-SIP/issues/6#issuecomment-318824002
