### ISSUE TITLE
SIP to WebRTC calls only one way audio

### ISSUE THREAD

**Issue by m1ggy** [havfo/WEBRTC-to-SIP#37]
Hi, I've deployed this project on a server and got it working, i can start calls vice versa (SIP <--> WebRTC, WebRTC<-->WebRTC) using the included browser SIP client and with other SIP clients as well but the issue is when i use Zoiper to call a Browser SIP client, I can only hear the voice from Zoiper. 

I haven't touched the config files for Kamailio and RTPEngine.

Any suggestions? thanks.

**Comment by havfo** [comment]
I have not tested Zoiper, but you would need to look at what the clients are actually signaling to find the problem.

The call is set up and actually running, just no audio from browser to Zoiper? What audio codec are they agreeing on?

**Comment by m1ggy** [comment]
hi @havfo, thank you for your reply. 
this is the invite SDP coming from Zoiper to the browser client
![image](https://user-images.githubusercontent.com/46958815/194095669-a0cb92cf-f909-480e-8dbc-4c505ddd1663.png)
and this is the OK SDP from the browser client to Zoiper
![image](https://user-images.githubusercontent.com/46958815/194095753-23a7d34c-db20-426f-ba53-2f1df0524741.png)
I am using UDP as transport. The call was initiated by Zoiper. also, the audio becomes one way when I access the video stream in Zoiper. The video appears and i can hear the audio on Zoiper but in the browser client no video and no audio at all.

Thanks.

**Comment by havfo** [comment]
Hmm...I am just guessing here, but the lack of RTCP from the Zoiper client may be the issue here. I suggest you look into the `generate RTCP` option for RTPEngine. I haven't actually used it myself, but from the description it should be nice to have anyway.

**Comment by m1ggy** [comment]
alright I'll take a look at the `generate RTCP` option. Also what softphone client do you use for testing? thanks.

**Comment by havfo** [comment]
I have usually used Blink. That being said, I haven't really been doing work in SIP for a couple of years now.
