### ISSUE TITLE
why use turn server, can I only use rtpengine？

### ISSUE THREAD

**Issue by Mr-houzi** [havfo/WEBRTC-to-SIP#39]
Hi，I have a question. I can not find turn server on Architecture graph. why use turn server, can I only use rtpengine？

**Comment by khorsmann** [comment]
You can use only rtpengine if udp is allowed for clients. The turn part is mainly for channeling tcp clients to udp cause rtpengine is not capable of tcp for payload

**Comment by havfo** [comment]
Webrtc requires a TURN server to function in as many network scenarios as possible. The same can be said for SIP, but SIP clients are usually deployed in a more controlled network environment.

**Comment by Mr-houzi** [comment]
Thank you very much！
