### ISSUE TITLE
SDP offer/answer issue

### ISSUE THREAD

**Issue by faizann** [havfo/WEBRTC-to-SIP#4]
Atleast at the writing of this ticket the offer/invite sdp headers both contain a=setup:actpass which causes chrome (didn't try any other browser) drop the call. rtp_engine is always adding actpass even with dtls=no or dtls-passive command line argument.

**Comment by havfo** [comment]
Relevant info from RFC5763.

o    The endpoint MUST use the setup attribute defined in [RFC4145].
      The endpoint that is the offerer MUST use the setup attribute
      value of setup:actpass and be prepared to receive a client_hello
      before it receives the answer.  The answerer MUST use either a
      setup attribute value of setup:active or setup:passive.  Note that
      if the answerer uses setup:passive, then the DTLS handshake will
      not begin until the answerer is received, which adds additional
      latency. setup:active allows the answer and the DTLS handshake to
      occur in parallel.  Thus, setup:active is RECOMMENDED.  Whichever
      party is active MUST initiate a DTLS handshake by sending a
      ClientHello over each flow (host/port quartet).

**Comment by faizann** [comment]
I read this part as well. But looks like the configurations for rtpengine in kamailio or the runtime argument for rtpengine --dtsl-passive don't cause any change. Whatever I set, the rtp engine keeps returning a=setup:actpass.

The default configs in github repo also don't help in this situation. Any ideas?

**Comment by havfo** [comment]
Have you tried rewriting the SDP manually to see if it acts as instructed, but re-writes the SDP wrong?

**Comment by havfo** [comment]
I just tested with the latest pull requests I merged and it seems to be behaving correctly.
```
SIP.js: INVITE
   |                                   ^
   |  setup:actpass                    |
   |                                   |   setup:active
   v                                   |
RTPEngine                           ******
   |                                   ^
   |  setup:actpass                    |
   |                                   |   setup:active
   v                                   |
Kurento: 200 OK
```
