### ISSUE TITLE
Audio issues from Webrtc to SIP

### ISSUE THREAD

**Issue by Voipdevel** [havfo/WEBRTC-to-SIP#41]
Hi @havfo ,

I have installed and configured kamailio and webrtc and rtpengine and turn server as per given step and also configured client as well.

I can able to register webrtc client and while making call to asterisk then there is no audio.

I have installed kamailio 5.4.4 and  rtpengine : 12.3.1.3-1~bpo11+1.

I have used same kamailio configuration file but there is not any audio so can you please advice for the same.

Thanks in advance

**Comment by PadScratchJohns** [comment]
Hey @Voipdevel 

Quick question: Are you behind NAT with your Kamailio/RTPengine.CoTURN VM? 

If you are the Kamailio may need a listener on private and advertise public and the RTPengine definitely needs this line:
`interface = internal/10.10.10.10;external/10.10.10.10!23.34.45.54`

Try that and see how you get on. 

John.

**Comment by PadScratchJohns** [comment]
Also use a supported version of Kamailio and one of the x.5 versions of RTPengine as they are the LTS versions. The guide [here](https://github.com/havfo/WEBRTC-to-SIP?tab=readme-ov-file#install-rtpengine)  specifically uses 11.5

**Comment by Voipdevel** [comment]
Hi @PadScratchJohns,

Thank you so much for your suggestion. I have already fixed the issues by making some  changes RTPENGINE configuration parameter's.

Thanks.
Voipdevel.

**Comment by Kuanlin-Chen** [comment]
> Hi @PadScratchJohns,
> 
> Thank you so much for your suggestion. I have already fixed the issues by making some changes RTPENGINE configuration parameter's.
> 
> Thanks. Voipdevel.

@Voipdevel I am having a similar issue and wondering what changes did you make?
