### ISSUE TITLE
sip.js and sdp error 488 

### ISSUE THREAD

**Issue by balabanferhat** [havfo/WEBRTC-to-SIP#5]
Hi, I did everything you said in readme. My kamailio version is 4.2.0

I am getting 488 from client side, as you said in readme
error fires from sip.js invalid description

```
if (!this.mediaHandler.hasDescription(request) || this.renderbody) {
    SIP.Timers.setTimeout(fireNewSession, 0);
  } else {
    this.hasOffer = true;
    this.mediaHandler.setDescription(request)
    .then(
      fireNewSession,
      function onFailure (e) {
        self.logger.warn('invalid description');
        self.logger.warn(e);
        request.reply(488);
      }
    );
  }
```
I have 2 accounts trying to invite each other one is windows chrome and the other is mac chrome.

in windows chrome it appers as 
Failed to parse SessionDescription. msid-semantic: Failed to get the value of attribute: msid

im mac chrome it appears as 
Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.

in server debug logs I see 488 errors.

May 29 14:53:36 eyonetisim /usr/sbin/kamailio[31781]: INFO: <script>: WebRTC -> SIP, bridging SRTP->RTP and removing ICE
May 29 14:53:36 eyonetisim /usr/sbin/kamailio[31782]: INFO: <script>: REPLY_TO_WS Reply from softphone: 100
May 29 14:53:36 eyonetisim /usr/sbin/kamailio[31782]: INFO: <script>: REPLY_TO_WS Reply from softphone: 488
May 29 14:53:36 eyonetisim /usr/sbin/kamailio[31782]: INFO: <script>: Failure: <null>

I checked everything in readme as you said , but do not understand this part and I think you want to say something about this 488 error here. You say "comment out the line #!define WITH_ALWAYS_BRIDGE in etc/kamailio/kamailio.cfg". What do you mean by comment out? If I remove this in line 11 #!define WITH_ALWAYS_BRIDGE   , I get compile error from kamailio.cfg file (invalid  route  statement) and kamailio does not start. Therefore I removed #!ifdef WITH_ALWAYS_BRIDGE and #!ifndef WITH_ALWAYS_BRIDGE from everywhere kamailio starts but nothing changes, error is same.

Please help me solving this 488 error. Is it related to rtpengine_manage flags or about Kamailio. I keep trying everything, when I remove route[RTP_BRIDGE] everything works if clients are in same network. But if not, clients do not get or share streams. Another error occurs in client side.

I really appreciate any help you can provide.

**Comment by havfo** [comment]
Hi, this setup is not built for bridging between WebRTC clients by default. The Kamailio config needs some modifications if that is to work. What call scenarios do you plan to support?

To disable WITH_ALWAYS_BRIDGE, change the line: 
#!define WITH_ALWAYS_BRIDGE
to
##!define WITH_ALWAYS_BRIDGE

**Comment by balabanferhat** [comment]
My call scenarios are **webrtc<>sip** ,  **webrtc<>webrtc**, **sip<>sip**

If I change the line like you said, I get compile errors  and cannot start kamailio

```
loading modules under config path: /usr/lib/x86_64-linux-gnu/kamailio/modules/
 0(7298) INFO: tls [tls_init.c:385]: init_tls_compression(): tls: init_tls: disabling compression...
 0(7298) : <core> [cfg.y:3439]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line **619**, column 1: syntax error
 0(7298) : <core> [cfg.y:3439]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line **619**, column 1: invalid  route  statement
 0(7298) : <core> [cfg.y:3436]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line **622**, column 1-12:
ERROR: bad config file (3 errors)
```

These lines ,619 and 622 can be seen below

My config file is same as yours. Nothing changed only XXXX parts are changed. 

```
route[RTP_BRIDGE] {
	#!ifdef WITH_ALWAYS_BRIDGE
	if (is_method("INVITE")) {
		if ($ru =~ "transport=ws") {
			xlog("L_INFO", "SIP -> WebRTC, bridging RTP->SRTP and adding ICE");
			rtpengine_manage("trust-address replace-origin replace-session-connection rtcp-mux-accept rtcp-mux-offer ICE=force UDP/TLS/RTP/SAVPF");
			t_on_reply("REPLY_FROM_WS");
		} else if ($proto =~ "ws") {
			xlog("L_INFO", "WebRTC -> SIP, bridging SRTP->RTP and removing ICE");
			rtpengine_manage("trust-address replace-origin replace-session-connection rtcp-mux-demux ICE=remove RTP/AVP");
			t_on_reply("REPLY_TO_WS");
		}
	}
	#!endif
}  <------------------619

# manage outgoing branches
branch_route[MANAGE_BRANCH] {   <------------------622
```

By the way, I am now trying only webrtc<>webrtc and I cannot get rid of this 488 error.

**Comment by havfo** [comment]
Ah, nice catch. A route block always needs to contain something, so put a logging statement or something there. Example:
```
route[RTP_BRIDGE] {
	xlog("L_INFO", "ROUTE: RTP_BRIDGE");
	#!ifdef WITH_ALWAYS_BRIDGE
...
```

Like I said, this configuration will not handle all those scenarios by default. The intended use of this configuration is to make WebRTC be able to call SIP and vice versa.

From your description of network issues, I suspect you haven't set up a turn server? The WebRTC clients shouldn't need a RTPEngine between them, the TURN server should be enough.

**Comment by balabanferhat** [comment]
Hi, thanks for your help. I managed to make calls  webrtc<>webrtc,  webrtc > sip and sip<>sip
but I can do it by changing configurations. How can I detect if call is webrtc<>webrtc  and change configuration dynamically?

**Comment by havfo** [comment]
Hi, I just pushed out a new config you can try. It's called kamailio-bridging.cfg. The new config should be smarter in handling the different types of bridging needed based on your needs.

**Comment by balabanferhat** [comment]
Thks, it is much smarter now, and all settings work **except video calls** between sip<>ws and sip<>sip. 

I tested phone calls they are all ok. 

for ws<> ws I commented rtpengine_manage and succeeded like this setup. I think we dont need bridging for this? 

```
route[SETUP_BRIDGING] {
	if(!has_totag()) {
		if ($proto =~ "ws") { # Coming from websocket
			if ($ru =~ "transport=ws") { # WebRTC > WebRTC
				xlog("L_INFO", "WebRTC > WebRTC");
				# rtpengine_manage("trust-address replace-origin replace-session-connection ICE=force");
				# t_on_reply("REPLY_WS_TO_WS");
			} else { # WebRTC > SIP
				xlog("L_INFO", "WebRTC > SIP");
				rtpengine_manage("trust-address replace-origin replace-session-connection rtcp-mux-demux ICE=remove RTP/AVP");
				t_on_reply("REPLY_WS_TO_SIP");
			}
		} else { # Coming from SIP
			if ($ru =~ "transport=ws") { # SIP > WebRTC
				xlog("L_INFO", "SIP > WebRTC");
				rtpengine_manage("trust-address replace-origin replace-session-connection rtcp-mux-accept rtcp-mux-offer ICE=force RTP/SAVPF");
				t_on_reply("REPLY_SIP_TO_WS");
			} else { # SIP > SIP
				xlog("L_INFO", "SIP > SIP");
				rtpengine_manage("trust-address replace-origin replace-session-connection");
				t_on_reply("REPLY_SIP_TO_SIP");
			}
		}
	}
}

```

For sip clients I use linphone. And video is not working in ios and android clients.  **Has kamailo a configuration to enable video-media streams ?**  .  I have seen that Zopier client has a setting rport that enables media and signaling. If I enable it video starts working. But in linphone there is no such a setting and Nat cannot be handled. Therefore, video works only if clients are in same network.

**Comment by havfo** [comment]
For your first question, you are right that you don't need bridging for all the cases, ws <> ws should be best without RtpEngine.

Regarding the video issue, I am not sure why this doesn't work. There is nothing in Kamailio that has antything to do with video in that sense. RtpEngine modifies the SDP, but doesn't disable streams. Kamailio by itself doesn't care what is in the SDP.

I just pushed out a config that **should** fix handling of NAT for SIP clients (haven't had time to test it).
