### ISSUE TITLE
Internal / external network setup

### ISSUE THREAD

**Issue by BertrandTotti** [havfo/WEBRTC-to-SIP#6]
Hello,

I am trying to setup Kamailio and rtpengine to listen simulatenaously to my internal and external network.
I have several sip clients on internal network registered to kamailio (without NAT).
I want bridgle all calls (signaling and media). My local network must keep isolated.
My use cases are :
Internal SIP Client <-> external SIP Client
Internal SIP Client <- external WebRTC client

Are these use cases easily realizable? What changes would be needed ?
Thanks.

**Comment by havfo** [comment]
This should be fairly straight forward. You need to make Kamailio listen to both the internal and external interface, take a look in the Kamailio [cookbook](https://www.kamailio.org/wiki/cookbooks/5.0.x/core#listen). Then you need to make RTPEngine do the same, take a look in the sample [config](https://github.com/sipwise/rtpengine/blob/master/etc/rtpengine.sample.conf) in their git repo, and also read up on the --interface section of their README.

Depending on how your network is set up, you probably have to change some of the rtpengine-calls in the Kamailio config, I'm guessing that there is no network route for your internal clients to reach the external interface on Kamailio/RTPEngine? In any case, use the newest [kamailio-bridging.conf](https://github.com/havfo/WEBRTC-to-SIP/blob/master/etc/kamailio/kamailio-bridging.cfg) config as your basis, it should be easier to modify for your usecase.

**Edit**: Take a look in the Kamailio [cookbook](https://www.kamailio.org/wiki/cookbooks/devel/core#dst_ip) for an example on how to detect the interface a packet came to. Using this info, specify the `direction` parameter to the rtpengine parameters.

Example: Two interfaces specified in RTPEngine called `int` and `ext`. For a call coming from an internal client, specify `direction=int direction=ext` in addition to whatever else you want to bridge. There is no need to specify the interfaces in the answer, RTPEngine handles that for you. The order of the `direction` flags are important, the originator is specified first.

**Comment by yboujraf** [comment]
Dear @havfo the kamailio-bridging.XING we get error 404.

Best regards

**Comment by yboujraf** [comment]
Dear @havfo ,

would you like to share the "kamailio-bridging.cfg"?

Best Regards

**Comment by havfo** [comment]
That file does not exist anymore, it evolved into the config today. If you want that file specifically, go back in git history to find it.
