### ISSUE TITLE
need to consulting to fix briding to work with asterisk behing the nat 

### ISSUE THREAD

**Issue by avbdr** [havfo/WEBRTC-to-SIP#7]
Hello, 
Are you available for a paid consulting work? 
Im breaking my head with a bridging issue i got. 

Thans. Please close an issue if you are not available for that.

**Comment by havfo** [comment]
Sorry for the late reply, busy weekend. I am not available for consulting work, too busy at the moment sorry. What is your problem?

**Comment by avbdr** [comment]
I have an asterisk servers in the private network and a kamailio with rtpengine in the front. Asterisk video seems only working with reinvite enabled so I got to a point where calls WEBRTC client -> kamailio -> asterisk -> back to kamailio -> sip are working but sip client -> kam -> asterisk -> back to kam -> other sip client doesnt have any video. on both sides.  
Not sure how to troubleshoot that case any further.

**Comment by havfo** [comment]
Have you checked that the SIP clients support the same codecs and that the video-part of the SDP is present when the SIP-message flows between kam -> asterisk -> kam?

**Comment by avbdr** [comment]
yes its all good. Issue where in asterisk side.  For others who will want to build video solution on asterisk its highly recommended to use asterisk14 and chan_pjsip. With Asterisk less then 13 its less likely to have a decent video at all.
