### ISSUE TITLE
how to register multiple register at WEBRTC

### ISSUE THREAD

**Issue by prashantvidja** [havfo/WEBRTC-to-SIP#8]
Hello

How can I register multiple user at WEBRTC ?
Now I am register only one user by default websip.
so how create different user and use for login at WEBRTC page?

Thanks

**Comment by havfo** [comment]
This project is only made as a starting point for a service, and the WebRTC page is hard coded to login to the `websip` user you make according to the README.

That said, if you want to create more users you can run the following command on the server running Kamailio `kamctl add username password` and change username and password to whatever you like.

**Comment by prashantvidja** [comment]
Thanks for help
