### ISSUE TITLE
getting error at chat conversation

### ISSUE THREAD

**Issue by prashantvidja** [havfo/WEBRTC-to-SIP#9]
hello 

I got error at chat conversation with every single message.
screenshot of error below attached.

Thanks
![untitled](https://user-images.githubusercontent.com/26060662/31990226-1c148ace-b992-11e7-9e00-c7bf13c70ad0.png)

**Comment by havfo** [comment]
I have not tested the chat functionality very much. Do you see any SIP errors in the console of the webbrowser? In my test setup it seems to work between two WebRTC participants.

**Comment by prashantvidja** [comment]
Thanks 
No i am not get any sip errior, this error due to some other reason
